#!/usr/bin/env node
// Generate assets/js/version.js from VERSION + git short SHA, at deploy time.
// Netlify exposes COMMIT_REF; locally we shell out to git.
const fs = require('node:fs');
const path = require('node:path');
const cp = require('node:child_process');

const ROOT = path.join(__dirname, '..');
const VERSION_FILE = path.join(ROOT, 'VERSION');
const OUT = path.join(ROOT, 'assets', 'js', 'version.js');

const semver = (fs.readFileSync(VERSION_FILE, 'utf8') || '').trim() || '0.0.0';

let sha = (process.env.COMMIT_REF || '').slice(0, 7);
if (!sha) {
  try {
    sha = cp.execSync('git rev-parse --short HEAD', { cwd: ROOT, encoding: 'utf8' }).trim();
  } catch (e) {
    sha = 'local';
  }
}

const branch = (process.env.BRANCH || process.env.HEAD || '').trim();
const builtAt = new Date().toISOString().slice(0, 10);

const body = `// Generated by scripts/build-version.js at deploy time. Do not edit.
window.SITE_VERSION = {
  semver: ${JSON.stringify(semver)},
  sha: ${JSON.stringify(sha)},
  branch: ${JSON.stringify(branch)},
  builtAt: ${JSON.stringify(builtAt)},
  display: ${JSON.stringify(`v${semver} · ${sha}${branch && branch !== 'main' ? ' · ' + branch : ''}`)},
};
`;
fs.writeFileSync(OUT, body, 'utf8');
console.log(`[build-version] wrote ${OUT}`);
console.log(`[build-version]   v${semver} · ${sha}${branch ? ' · ' + branch : ''}`);
